name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore

    #build
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    #package
    - name: Package NUGET
      run: dotnet pack --configuration Release
    - name: Publish to NUGET
      uses: brandedoutcast/publish-nuget@v2.5.4
      with:
          PROJECT_FILE_PATH: Rave.NET/Rave.NET.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}